### ISSUE TITLE
having "What's New" info

### ISSUE THREAD

**Issue by blizzz** [nextcloud-releases/updater_server#115]
For https://github.com/nextcloud/server/issues/9163 we require to have up to 3 bullet points of "What's new" info for an upcoming release. The text will be prepared by @jospoortvliet or his team. 

Options:

* (original ifea) a file in the nextcloud.com server repo, but this means overhead for the updater_server (fetching, caching)
* entries in the config/config.php, but they'd be duplicated and bloated
* a new file, perhaps config/whatsnew.json, in JSON format, that would be read and added to the reply. It would contain an array with version acting as a key, being an  array carrying up to three strings.

I guess the last option makes most sense.

What do you think @MorrisJobke @nickvergessen

**Comment by joshtrichards** [comment]
I believe #116 means this can be closed (unless I'm overlooking something).

**Comment by skjnldsv** [comment]
How did you find this @joshtrichards :sweat_smile:

**Comment by joshtrichards** [comment]
I probably fell down some rabbit hole, but it was instigated by some Updater related doc work. :smile:

**Comment by skjnldsv** [comment]
I see we stopped providing the what's new data for a while, probably not required anymore
